#!/bin/bash

appdir=/install/scripts


if [[ $1 == "install" ]];then
    /bin/bash $appdir/library/install
fi

if [[ $1 == "build" ]];then
   /bin/bash $appdir/library/build
fi

if [[ $1 == "deploy" ]];then
   /bin/bash $appdir/library/deploy
fi

if [[ $1 == "update" ]];then
    echo "pull repository" && git pull && 
    echo "populating file" && git add . &&
    echo "commit  changes" && git commit -m "$(date)" &&
    echo "push to gitrepo" && git push
fi